# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: BYP
email: youngeric@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  When you place an order, it will be reviewed by a BYP account executive. If
  more information is needed, s/he will need to contact you before it can be
  sent to production. Please make sure you include your contact number on the
  order form.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ericyoung
github_username:  ericyoung
# timezone: America/Chicago
# encoding: "utf-8"
# plugins_dir:  _plugins
# layouts_dir:  _layouts
# data_dir:     _data
# includes_dir: _includes


# Build settings
markdown: kramdown
# theme: forty-jekyll-theme
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
